project_id = "hmshfuvjzixoinblmagv"

[functions.fetch-place-rating]
verify_jwt = false

[functions.daily-google-refresh]
verify_jwt = false

[functions.fetch-tripadvisor-rating]
verify_jwt = false

[functions.fetch-booking-rating]
verify_jwt = false

[functions.fetch-expedia-rating]
verify_jwt = false

[functions.analyze-reviews]
verify_jwt = false

[functions.fetch-reviews]
verify_jwt = false

[functions.resolve-hotel-urls]
verify_jwt = false

[functions.place-autocomplete]
verify_jwt = false